name: Deploy to LangSmith

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate configuration
        run: |
          python -m json.tool langgraph.json
          echo "✓ Configuration valid"

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run tests
        run: pytest tests/

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Trigger deployment
        run: |
          echo "Deployment triggered via push to main branch"
          echo "LangSmith will automatically deploy from GitHub"
